### PR TITLE
add example of solving using LU for Ax=b

### PR DESCRIPTION
**Pull request by DevinBayly**
Please let me know if you would like me to add any more information, but this is the kind of thing that would have answered my question without posting in the discord chat. Hopefully people will see it when they are looking for a concrete case of how to run a simple solve. Thanks for working on this project!

### CODE REVIEW

**Comment by sebcrozet** [comment]
Thanks! It would be great if:

1. You used `m.lu()` instead of `linalg::LU::new`.
2. You added spaces after each comma for the matrix and vector construction as in `Vector4::new(3.0, -3.0, -11.0, -5.0)`
1. The example would include an example for `.solve_mut` too.
2. To add a list (or a table) that mentions the other decompositions that support resolution of linear systems: `QR`, `Cholesky` and `SVD`. It would also be mentioned that `Cholesky` is the most efficient approach for symmetric-definite-positive matrices, and that `SVD` allow the resolution with non-invertible matrices.
3. Mention that the point of building a matrix decomposition before actually solving linear systems is to be able to solve efficiently several linear systems involving the same `A` but different values of `b`.

Depending on your background on linear algebra, please let me know if you feel comfortable providing the explanations for 4 and 5, or if you prefer I do.

**Comment by DevinBayly** [comment]
Thanks for the suggestions, they're  instructive for me also. I haven't
done much with cholesky, and svd was used in my linear proofs class but
that was a while ago. Ill tackle 1-3 in a moment though.

--Sent from the smartphone, please excuse brevity and typos.--

**Comment by sebcrozet** [comment]
Thanks! I will merge and complete the details next saturday.

**Comment by DevinBayly** [comment]
Great! Thanks for stepping in with the higher level information.

--Sent from the smartphone, please excuse brevity and typos.--

**Pull request merged**
